name: luacheck

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install luacheck
              run: sudo apt-get --install-recommends -y install luarocks
